In [1]:
import numpy as np
from pathlib import Path
import os


In [2]:
rotation_matrices = np.load('/home/gregorian/projects/composed-robot-desktop/computer_vision/aruco_location/rotation_matrices.npy')
translation_vectors = np.load('/home/gregorian/projects/composed-robot-desktop/computer_vision/aruco_location/translation_vectors.npy')

In [3]:
rotation_matrices

array([[[ 0.97353662,  0.03489696,  0.22585094],
        [-0.04184987, -0.94433679,  0.32630754],
        [ 0.22466649, -0.32712417, -0.91788602]],

       [[ 0.97353662,  0.03489696,  0.22585094],
        [-0.04184987, -0.94433679,  0.32630754],
        [ 0.22466649, -0.32712417, -0.91788602]],

       [[ 0.97353662,  0.03489696,  0.22585094],
        [-0.04184987, -0.94433679,  0.32630754],
        [ 0.22466649, -0.32712417, -0.91788602]],

       ...,

       [[ 0.97353662,  0.03489696,  0.22585094],
        [-0.04184987, -0.94433679,  0.32630754],
        [ 0.22466649, -0.32712417, -0.91788602]],

       [[ 0.97012365,  0.04179674,  0.23898355],
        [-0.04105952, -0.94255335,  0.3315227 ],
        [ 0.23911131, -0.33143057, -0.91267714]],

       [[ 0.97353662,  0.03489696,  0.22585094],
        [-0.04184987, -0.94433679,  0.32630754],
        [ 0.22466649, -0.32712417, -0.91788602]]], shape=(300, 3, 3))

In [4]:
translation_vectors

array([[-85.72502573, -59.49271161, 523.80470338],
       [-85.72502573, -59.49271161, 523.80470338],
       [-85.72502573, -59.49271161, 523.80470338],
       [-85.72502573, -59.49271161, 523.80470338],
       [-85.72502573, -59.49271161, 523.80470338],
       [-85.72502573, -59.49271161, 523.80470338],
       [-85.72502573, -59.49271161, 523.80470338],
       [-85.72502573, -59.49271161, 523.80470338],
       [-85.72502573, -59.49271161, 523.80470338],
       [-85.72502573, -59.49271161, 523.80470338],
       [-85.72502573, -59.49271161, 523.80470338],
       [-85.72502573, -59.49271161, 523.80470338],
       [-85.72502573, -59.49271161, 523.80470338],
       [-85.72502573, -59.49271161, 523.80470338],
       [-85.72502573, -59.49271161, 523.80470338],
       [-85.72502573, -59.49271161, 523.80470338],
       [-85.72502573, -59.49271161, 523.80470338],
       [-93.25174525, -61.96633978, 520.42231156],
       [-85.72502573, -59.49271161, 523.80470338],
       [-85.72502573, -59.49271

In [5]:
median_rotation = np.median(rotation_matrices,axis=0)
median_rotation

array([[ 0.97353662,  0.03489696,  0.22585094],
       [-0.04184987, -0.94433679,  0.32630754],
       [ 0.22466649, -0.32712417, -0.91788602]])

In [6]:
median_translation = np.median(translation_vectors,axis=0)
median_translation

array([-85.72502573, -59.49271161, 523.80470338])