In [1]:
import numpy as np
from composed_robot.utilities.geometry import intersection_plane_and_line,get_normal_of_plane,to_homogenous,transform_vectors,drop_homogenous

In [2]:
#tested on link in previous cell

point_on_line = np.array([2,1,0])
vector_along_line = np.array([-1,1,3])

normal_to_plane = np.array([3,-2,1])
point_on_plane = np.array([0,0,10])
intersection_plane_and_line(point_on_plane,normal_to_plane,point_on_line,vector_along_line)

-3.0


array([ 5., -2., -9.])

In [3]:
#tested on example 11.3 practical linear algebra

point_on_line = np.array([1,1,2])
vector_along_line = np.array([0,0,1])

normal_to_plane = np.array([1,1,1])

# dont need to normalize n but just doing it here as generally i will deal with normalised n
normal_to_plane = normal_to_plane/np.linalg.norm(normal_to_plane)
point_on_plane = np.array([0,0,1])
intersection_plane_and_line(point_on_plane,normal_to_plane,point_on_line,vector_along_line)

-3.0


array([ 1.,  1., -1.])

In [4]:

to_homogenous(np.array([[1,23,1],[1,4,5]]))

array([[ 1., 23.,  1.,  1.],
       [ 1.,  4.,  5.,  1.]])

In [5]:

h_points = to_homogenous(np.array([[1,23,1],[1,4,5]]))
print(h_points)
drop_homogenous(h_points)

[[ 1. 23.  1.  1.]
 [ 1.  4.  5.  1.]]


array([[ 1., 23.,  1.],
       [ 1.,  4.,  5.]])

In [6]:
#working out finding distance along optical axis to gnd plane
#the matrix bellow was actually determined on the robot

c_T_m = np.array([[ 9.99827996e-01 ,-2.27670966e-03 , 1.84063655e-02 ,-1.13412592e+02],
 [ 6.01109719e-03, -8.99086289e-01 ,-4.37730181e-01, -2.02601123e+02],
 [ 1.75454954e-02 , 4.37765533e-01, -8.98917957e-01 , 6.48697949e+02],
 [ 0.00000000e+00 , 0.00000000e+00  ,0.00000000e+00,  1.00000000e+00]])

In [7]:
#points on plane w.r.t Marker
#z axis has to be 0 x and y can be anything

m_P = to_homogenous(np.array([[0,0,0],[0,1,0],[1,0,0]]))
m_P

array([[0., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.]])

In [8]:
# points on plane w.r.t camera
c_P = transform_vectors(c_T_m,m_P)
c_P = drop_homogenous(c_P)

In [9]:
normal_vector_of_plane = get_normal_of_plane(c_P)
normal_vector_of_plane

array([-0.01840637,  0.43773018,  0.89891796])

In [10]:
point_on_plane = c_P[0]
point_on_plane

array([-113.412592, -202.601123,  648.697949])

In [11]:
point_on_line_1 = np.array([0,0,0])
point_on_line_2 = np.array([0,0,1])
vector_along_line = point_on_line_2-point_on_line_1

In [12]:
#expected value of z from calculations is 554.931 so this is quite good.
intersection_plane_and_line(point_on_plane,normal_vector_of_plane,point_on_line_1,vector_along_line)

552.363114371243


array([  0.        ,   0.        , 552.36311437])

In [15]:
def point_to_homogenous(point):
  result = np.array([0,0,0,1])
  result[0:3]=point.copy()
  return result

In [16]:
point_to_homogenous(np.array([1,2,3]))

array([1, 2, 3, 1])