In [3]:
import numpy as np

In [4]:
contours = np.load('/home/gregorian/projects/composed-robot-desktop/computer_vision/tyre_tracker/contours.npy')

EOFError: No data left in file

In [23]:
contour_sizes = np.array([300.0,700.25,30,1200,4000,5,10,400,500])

In [25]:

sorted_indexes = np.argsort(contour_sizes)
sorted_indexes

array([5, 6, 2, 0, 7, 8, 1, 3, 4])

In [20]:
contour_sizes_sorted = contour_sizes[sorted_indexes]
contour_sizes_sorted

array([4000, 1200,  700,  500,  400,  300,   30,   10,    5])

In [21]:
contour_sizes_sorted>200

array([ True,  True,  True,  True,  True,  True, False, False, False])

In [14]:
np.argmax((contour_sizes_sorted>200) & (contour_sizes_sorted<1000))

np.int64(3)

In [16]:
(contour_sizes_sorted>200) & (contour_sizes_sorted<1000)

array([False, False, False,  True,  True,  True,  True, False, False])

In [17]:
np.argmax([False,False])

np.int64(0)

In [18]:
np.array([False,False]).sum()

np.int64(0)