In [1]:
import numpy as np
from pathlib import Path
import os


In [7]:
rotation_matrices = np.load('/home/gregorian/projects/composed-robot-desktop/computer_vision/aruco_location/rotation_matrices.npy')
translation_vectors = np.load('/home/gregorian/projects/composed-robot-desktop/computer_vision/aruco_location/translation_vectors.npy')

In [4]:
rotation_matrices

array([[[ 0.99865319, -0.02889067,  0.04309454],
        [-0.04226235, -0.93478724,  0.35268499],
        [ 0.03009492, -0.35403127, -0.93474925]],

       [[ 0.99914478, -0.02529386,  0.03270989],
        [-0.03552455, -0.92992515,  0.36602898],
        [ 0.02115946, -0.36687795, -0.93002841]],

       [[ 0.99865319, -0.02889067,  0.04309454],
        [-0.04226235, -0.93478724,  0.35268499],
        [ 0.03009492, -0.35403127, -0.93474925]],

       [[ 0.99890097, -0.02732713,  0.0380798 ],
        [-0.03925281, -0.93172378,  0.36104018],
        [ 0.02561367, -0.36213813, -0.93177246]],

       [[ 0.99890097, -0.02732713,  0.0380798 ],
        [-0.03925281, -0.93172378,  0.36104018],
        [ 0.02561367, -0.36213813, -0.93177246]],

       [[ 0.99890097, -0.02732713,  0.0380798 ],
        [-0.03925281, -0.93172378,  0.36104018],
        [ 0.02561367, -0.36213813, -0.93177246]],

       [[ 0.99865319, -0.02889067,  0.04309454],
        [-0.04226235, -0.93478724,  0.35268499],
        

In [8]:
translation_vectors

array([[ 117.72147069, -460.61358612,  562.56324534],
       [ 124.25285677, -462.14324488,  548.4987428 ],
       [ 117.72147069, -460.61358612,  562.56324534],
       [ 121.02265276, -462.19425189,  554.3864495 ],
       [ 121.02265276, -462.19425189,  554.3864495 ],
       [ 121.02265276, -462.19425189,  554.3864495 ],
       [ 117.72147069, -460.61358612,  562.56324534],
       [ 121.02265276, -462.19425189,  554.3864495 ],
       [ 121.0933894 , -460.67071796,  556.57841212],
       [ 117.72147069, -460.61358612,  562.56324534],
       [ 121.02265276, -462.19425189,  554.3864495 ],
       [ 121.02265276, -462.19425189,  554.3864495 ],
       [ 124.25285677, -462.14324488,  548.4987428 ],
       [ 121.0933894 , -460.67071796,  556.57841212],
       [ 117.72147069, -460.61358612,  562.56324534],
       [ 117.72147069, -460.61358612,  562.56324534],
       [ 121.02265276, -462.19425189,  554.3864495 ],
       [ 121.02265276, -462.19425189,  554.3864495 ],
       [ 117.72147069, -460.

In [6]:
median_rotation = np.median(rotation_matrices,axis=0)
median_rotation

array([[ 0.99890097, -0.02732713,  0.0380798 ],
       [-0.03925281, -0.93300009,  0.35780971],
       [ 0.02561367, -0.35887594, -0.93303723]])

In [9]:
median_translation = np.median(translation_vectors,axis=0)
median_translation

array([ 121.02265276, -460.67071796,  556.57841212])